[book]
src = "src"
title = "Rust on Mobile"
authors = ["Ghamza-Jd"]
language = "en"
description = "Building a Rust library and use it across platforms"
multilingual = false

[output.html]
cname = "native-rust-lib.ghamza.dev"
default-theme = "light"
google-analytics = "G-M9GYS9Z1XC"
git-repository-url = "https://github.com/ghamza-rust/ghamza-rust.github.io"
git-repository-icon = "fa-github"
preferred-dark-theme = "navy"

[output.html.playground]
runnable = false

[preprocessor.plantuml]
plantuml-cmd = "http://www.plantuml.com/plantuml"
use-data-uris = true
